### ISSUE TITLE
InitiateEptFunctionAddressArrays  unexpected behavior

### ISSUE THREAD

**Issue by pythonfansx** [donnaskiez/ac#8]
I found a typo in the function InitiateEptFunctionAddressArrays while reviewing the code, which caused the function not to meet the unexpected behavior.

for (INT index = 0; index < EPT_PROTECTED_FUNCTIONS_COUNT; index++) {
    UNICODE_STRING current_function;
    RtlInitUnicodeString(&current_function, CONTROL_FUNCTIONS[index]);
    PROTECTED_FUNCTION_ADDRESSES[index] =
        MmGetSystemRoutineAddress(&current_function);

It should be corrected to:

for (INT index = 0; index < EPT_PROTECTED_FUNCTIONS_COUNT; index++) {
     RtlInitUnicodeString(&current_function, PROTECTED_FUNCTIONS[index]);
     PROTECTED_FUNCTION_ADDRESSES[index] =
	MmGetSystemRoutineAddress(&current_function);
Please correct the code in the subsequent version.  thank you    :}

**Comment by donnaskiez** [comment]
thanks, fixed

https://github.com/donnaskiez/ac/commit/23444671ea58281ca1c2efc67deb4e0aeeaaec4b
